/**
 * Types of notifications in the TerraField Mobile app
 */
export enum NotificationType {
  PHOTO_ENHANCEMENT_STARTED = 'PHOTO_ENHANCEMENT_STARTED',
  PHOTO_ENHANCEMENT_COMPLETED = 'PHOTO_ENHANCEMENT_COMPLETED',
  PHOTO_ENHANCEMENT_FAILED = 'PHOTO_ENHANCEMENT_FAILED',
  SYNC_STARTED = 'SYNC_STARTED',
  SYNC_COMPLETED = 'SYNC_COMPLETED',
  SYNC_FAILED = 'SYNC_FAILED',
  NEW_PHOTO_AVAILABLE = 'NEW_PHOTO_AVAILABLE',
  OFFLINE_QUEUE_UPDATED = 'OFFLINE_QUEUE_UPDATED',
}