version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: terra
      POSTGRES_USER: terra
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: ["pnpm", "dev"]
    ports:
      - 5000:5000
    depends_on:
      - db

  client:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: ["pnpm", "dev"]
    ports:
      - 3000:3000

volumes:
  db_data:
