global:
  resolve_timeout: 5m
  smtp_from: 'alertmanager@terrafusion.com'
  smtp_smarthost: 'smtp.example.com:587'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-notifications'
  routes:
  - match:
      severity: critical
    receiver: 'pager-notifications'
    continue: true
  - match_re:
      severity: ^(warning|info)$
    receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'alerts@terrafusion.com'
    send_resolved: true

- name: 'pager-notifications'
  webhook_configs:
  - url: 'http://pager-service:8080/trigger-alert'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'job']